// Better Auth Configuration Template for Next.js
// Generated by Auth Integrator Skill
// Fill in placeholders based on spec

import { betterAuth } from "better-auth";

export const auth = betterAuth({
  baseURL: process.env.NEXT_PUBLIC_API_URL || "http://localhost:3000",
  secret: process.env.BETTER_AUTH_SECRET,
  jwt: {
    expiresIn: "1h", // Token expiration
  },
  // Add signin/signup handlers
  async signIn({ email, password }) {
    // Custom signin logic
    return { user: { id: "user_id", email } }; // Mock; replace with actual
  },
  // Session callback to include JWT
  callbacks: {
    session({ session, token }) {
      session.user.id = token.sub;
      return session;
    },
  },
});

// Usage in API client: Add token to headers
export const apiClient = {
  async fetch(endpoint: string, options: RequestInit) {
    const { data: session } = useSession();
    const headers = {
      ...options.headers,
      Authorization: `Bearer ${session?.token}`,
    };
    return fetch(`/api${endpoint}`, { ...options, headers });
  },
};