openapi: 3.0.3
info:
  title: Todo Tasks API
  description: REST API for managing user tasks with JWT authentication
  version: 1.0.0
  contact:
    name: Phase 2 Full-Stack Todo Application
servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.yourdomain.com
    description: Production server

security:
  - BearerAuth: []

paths:
  /api/tasks:
    get:
      summary: List all user's tasks
      description: Returns all tasks belonging to the authenticated user with optional filtering and sorting
      tags:
        - Tasks
      parameters:
        - name: status
          in: query
          description: Filter by task status
          required: false
          schema:
            type: string
            enum: [pending, completed, overdue]
        - name: sort_by
          in: query
          description: Field to sort by
          required: false
          schema:
            type: string
            enum: [due_date, priority, status, created_at]
            default: created_at
        - name: order
          in: query
          description: Sort order
          required: false
          schema:
            type: string
            enum: [asc, desc]
            default: desc
      responses:
        '200':
          description: Successfully retrieved tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskRead'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

    post:
      summary: Create a new task
      description: Creates a new task for the authenticated user
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskRead'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /api/tasks/{task_id}:
    get:
      summary: Get a single task
      description: Returns task details if the authenticated user owns the task
      tags:
        - Tasks
      parameters:
        - $ref: '#/components/parameters/TaskId'
      responses:
        '200':
          description: Successfully retrieved task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskRead'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'

    put:
      summary: Update a task
      description: Updates task fields for the authenticated user's task
      tags:
        - Tasks
      parameters:
        - $ref: '#/components/parameters/TaskId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskRead'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'

    delete:
      summary: Delete a task
      description: Permanently deletes a task owned by the authenticated user
      tags:
        - Tasks
      parameters:
        - $ref: '#/components/parameters/TaskId'
      responses:
        '204':
          description: Task deleted successfully
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'

  /api/tasks/{task_id}/complete:
    patch:
      summary: Mark task as completed
      description: Changes task status to completed (idempotent operation)
      tags:
        - Tasks
      parameters:
        - $ref: '#/components/parameters/TaskId'
      responses:
        '200':
          description: Task marked as completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskRead'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token from Better-Auth (include as "Bearer <token>")

  parameters:
    TaskId:
      name: task_id
      in: path
      required: true
      description: UUID of the task
      schema:
        type: string
        format: uuid
      example: "550e8400-e29b-41d4-a716-446655440000"

  schemas:
    TaskCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          maxLength: 200
          minLength: 1
          description: Task title
          example: "Buy groceries"
        description:
          type: string
          maxLength: 2000
          nullable: true
          description: Detailed task description
          example: "Need milk, bread, and eggs from the store"
        due_date:
          type: string
          format: date
          nullable: true
          description: Task deadline (ISO 8601 format YYYY-MM-DD)
          example: "2025-12-20"
        priority:
          type: string
          enum: [low, medium, high]
          default: medium
          description: Task priority level
          example: "high"

    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          maxLength: 200
          minLength: 1
          description: Updated task title
          example: "Buy groceries and supplies"
        description:
          type: string
          maxLength: 2000
          nullable: true
          description: Updated task description
        due_date:
          type: string
          format: date
          nullable: true
          description: Updated deadline
        priority:
          type: string
          enum: [low, medium, high]
          description: Updated priority

    TaskRead:
      type: object
      required:
        - id
        - user_id
        - title
        - priority
        - status
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
          description: Unique task identifier
          example: "550e8400-e29b-41d4-a716-446655440000"
        user_id:
          type: string
          format: uuid
          description: ID of the user who owns this task
          example: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        title:
          type: string
          maxLength: 200
          description: Task title
          example: "Buy groceries"
        description:
          type: string
          maxLength: 2000
          nullable: true
          description: Task description
          example: "Need milk, bread, and eggs"
        due_date:
          type: string
          format: date
          nullable: true
          description: Task deadline
          example: "2025-12-20"
        priority:
          type: string
          enum: [low, medium, high]
          description: Task priority
          example: "high"
        status:
          type: string
          enum: [pending, completed]
          description: Task completion status
          example: "pending"
        created_at:
          type: string
          format: date-time
          description: Task creation timestamp (UTC)
          example: "2025-12-11T10:30:00Z"
        updated_at:
          type: string
          format: date-time
          description: Last modification timestamp (UTC)
          example: "2025-12-11T15:45:00Z"

    ErrorResponse:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          description: Error message
          example: "Invalid token"

  responses:
    ValidationError:
      description: Request validation error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            detail: "Title is required"

    UnauthorizedError:
      description: Authentication required or invalid token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            detail: "Invalid token"

    ForbiddenError:
      description: User does not own this resource
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            detail: "Access denied"

    NotFoundError:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            detail: "Task not found"
