# SQLModel Models Template
# Generated by DB Schema Creator Skill
# Customize based on spec: Add fields, indexes, relationships

from sqlmodel import SQLModel, Field, Relationship, Index
from typing import Optional, List
from datetime import datetime

class BaseModel(SQLModel):
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

# Example Table (e.g., Task)
class TableName(BaseModel, table=True):
    __tablename__ = "table_name"
    __table_args__ = (Index("ix_field_name", "field_name"),)  # Add indexes

    id: int = Field(default=None, primary_key=True)
    # Add fields: e.g., title: str = Field(max_length=200)
    # Foreign keys: user_id: str = Field(foreign_key="users.id")
    # Relationships: user: Optional["User"] = Relationship(back_populates="tasks")