// Next.js Component Template
// Generated by UI Component Builder Skill
// Customize based on spec: Add props, state, handlers

import React from 'react';
// Import { api } from '@/lib/api'; // For API calls

interface Props {
  // Define props here, e.g., tasks: Task[]
}

export default function ComponentName({ /* props */ }: Props) {
  // Add state or hooks if client component
  // const [state, setState] = useState(initial);

  return (
    <div className="container mx-auto p-4">
      {/* Content here, e.g., form or list */}
      <h1 className="text-2xl font-bold">Component Title</h1>
    </div>
  );
}